DungeonMasterStudio/Models/CharacterModel.cs
using System.ComponentModel.DataAnnotations;

namespace DungeonMasterStudio.Models
{
    public class CharacterModel
    {
        [Key]
        public int ID { get; set; }
        [Required]  
        public string UserID { get; set; }
        [Required]
        public string Name { get; set; }
        public string? Class { get; set; }
        public string? Level { get; set; }
        public string? Race { get; set; }
        public string? Age1 { get; set; }
        public string? ArmorClass { get; set; }
        public string? CurrentHitPoints { get; set; }
        public string? MaxHitPoints { get; set; }
        public string? Strength { get; set; }
        public string? Dexterity { get; set; }
        public string? Constitution { get; set; }
        public string? Intelligence { get; set; }
        public string? Wisdom { get; set; }
        public string? Charisma { get; set; }
        public string? BackStory { get; set; }
        public string? Notes { get; set; }
        public DateTime Date { get; set; } = DateTime.Now;
    }
}

DungeonMasterStudio/Controllers/CharacterModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DungeonMasterStudio.Data;
using DungeonMasterStudio.Models;
using Microsoft.AspNetCore.Identity;
using DungeonMasterStudio.Helpers;
using Microsoft.AspNetCore.Authorization;

namespace DungeonMasterStudio.Controllers
{
    public class CharacterModelsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public CharacterModelsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager; 
        }

        // GET: CharacterModels
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Characters.Where(x => x.UserID == _userManager.GetUserId(HttpContext.User)).ToListAsync());
        }

        // GET: CharacterModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var characterModel = await _context.Characters
                .FirstOrDefaultAsync(m => m.ID == id);
            if (characterModel == null)
            {
                return NotFound();
            }

            return View(characterModel);
        }

        // GET: CharacterModels/Create
        public IActionResult Create()
        {
            Random rnd = new Random();
            ViewData["Class"] = RandomLists.GetClasses()[rnd.Next(0, RandomLists.GetClasses().Count)];
            ViewData["Age"] = RandomLists.GetAges()[rnd.Next(0, RandomLists.GetAges().Count)];
            ViewData["Race"] = RandomLists.GetRaces()[rnd.Next(0, RandomLists.GetRaces().Count)];
            ViewData["Name"] = RandomLists.GetFirstNames()[rnd.Next(0, RandomLists.GetFirstNames().Count)] +" "+ RandomLists.GetLastNames()[rnd.Next(0, RandomLists.GetLastNames().Count )];

            ViewData["Strength"] = GetModifier(GetAtribute()).ToString();
            ViewData["Dexterity"] = GetModifier(GetAtribute()).ToString();
            ViewData["Intelligence"] = GetModifier(GetAtribute()).ToString();
            ViewData["Constitution"] = GetModifier(GetAtribute()).ToString();
            ViewData["Wisdom"] = GetModifier(GetAtribute()).ToString();
            ViewData["Charisma"] = GetModifier(GetAtribute()).ToString();
            return View();
        }
        private int GetAtribute()
        {
            Dice die1 = new Dice(6);
            Dice die2 = new Dice(6);
            Dice die3 = new Dice(6);
            Dice die4 = new Dice(6);
            int sum = 0;


            List<int> Rolls = new List<int>();
            Rolls.Add(die1.Roll());
            Rolls.Add(die2.Roll());
            Rolls.Add(die3.Roll());
            Rolls.Add(die4.Roll());

            for (int i = 0; i < Rolls.Count; i++)
            {
                if (Rolls[i] == Rolls.Min())
                {
                    Rolls.RemoveAt(i);
                    break;
                }

            }


            for (int i = 0; i < Rolls.Count; i++)
            {
                sum += Rolls[i];
            }

            return sum;
        }

        private int GetModifier(int sum)
        {
            if (sum == 1)
            {
                return -5;
            }
            else if (sum == 2 || sum == 3)
            {
                return -4;
            }
            else if (sum == 4 || sum == 5)
            {
                return -3;
            }
            else if (sum == 6 || sum == 7)
            {
                return -2;
            }
            else if (sum == 8 || sum == 9)
            {
                return -1;
            }
            else if (sum == 10 || sum == 11)
            {
                return 0;
            }
            else if (sum == 12 || sum == 13)
            {
                return 1;
            }
            else if (sum == 14 || sum == 15)
            {
                return 2;
            }
            else if (sum == 16 || sum == 17)
            {
                return 3;
            }
            else
            {
                return 4;
            }
        }
        // POST: CharacterModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CharacterModel characterModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(characterModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(characterModel);
        }

        // GET: CharacterModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var characterModel = await _context.Characters.FindAsync(id);
            if (characterModel == null)
            {
                return NotFound();
            }
            return View(characterModel);
        }

        // POST: CharacterModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Class,Level,Race,Age1,ArmorClass,CurrentHitPoints,MaxHitPoints,Strength,Dexterity,Constitution,Intelligence,Wisdom,Charisma,BackStory,Notes,Date")] CharacterModel characterModel)
        {
            if (id != characterModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(characterModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharacterModelExists(characterModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(characterModel);
        }

        // GET: CharacterModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var characterModel = await _context.Characters
                .FirstOrDefaultAsync(m => m.ID == id);
            if (characterModel == null)
            {
                return NotFound();
            }

            return View(characterModel);
        }

        // POST: CharacterModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var characterModel = await _context.Characters.FindAsync(id);
            _context.Characters.Remove(characterModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CharacterModelExists(int id)
        {
            return _context.Characters.Any(e => e.ID == id);
        }
    }
}

DungeonMasterStudio/Views/CharacterModels/Create.cshtml
@using Microsoft.AspNetCore.Identity
@model DungeonMasterStudio.Models.CharacterModel

@inject UserManager<ApplicationUser> userManager

@{
 
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>CharacterModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <a class="btn btn-primary" href="@Url.Action("Create","CharacterModels")">Randomize</a>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="UserID" value="@userManager.GetUserId(User)" /> 
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" value="@ViewData["Name"]" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" value="@ViewData["Class"]" class="form-control" />
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Race" class="control-label"></label>
                <input asp-for="Race" value="@ViewData["Race"]" class="form-control" />
                <span asp-validation-for="Race" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age1" class="control-label"></label>
                <input asp-for="Age1" value="@ViewData["Age"]" class="form-control" />
                <span asp-validation-for="Age1" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Strength" class="control-label"></label>
                <input asp-for="Strength" value="@ViewData["Strength"]" class="form-control" />
                <span asp-validation-for="Strength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dexterity" class="control-label"></label>
                <input asp-for="Dexterity" value="@ViewData["Dexterity"]" class="form-control" />
                <span asp-validation-for="Dexterity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Constitution" class="control-label"></label>
                <input asp-for="Constitution" value="@ViewData["Constitution"]" class="form-control" />
                <span asp-validation-for="Constitution" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Intelligence" class="control-label"></label>
                <input asp-for="Intelligence" value="@ViewData["Intelligence"]" class="form-control" />
                <span asp-validation-for="Intelligence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wisdom" class="control-label"></label>
                <input asp-for="Wisdom" value="@ViewData["Wisdom"]" class="form-control" />
                <span asp-validation-for="Wisdom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Charisma" class="control-label"></label>
                <input asp-for="Charisma" value="@ViewData["Charisma"]" class="form-control" />
                <span asp-validation-for="Charisma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BackStory" class="control-label"></label>
                <input asp-for="BackStory" class="form-control" />
                <span asp-validation-for="BackStory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

DungeonMasterStudio/Views/CharacterModels/Delete.cshtml
@model DungeonMasterStudio.Models.CharacterModel

@{
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<div class="background-container">
    <h3>Are you sure you want to delete this?</h3>

    <h4>NPC Info</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Class)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Race)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Race)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age1)
        </dd>
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Strength)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Strength)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dexterity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dexterity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Constitution)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Constitution)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Intelligence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Intelligence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wisdom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wisdom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Charisma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Charisma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BackStory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BackStory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-primary" >Back to List</a>
    </form>
</div>
</body>
</html>

DungeonMasterStudio/Views/CharacterModels/Details.cshtml
@model DungeonMasterStudio.Models.CharacterModel

@{

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div class="background-container">
    <h4>NPC Info</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Class)
        </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Race)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Race)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age1)
        </dd>
        
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Strength)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Strength)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dexterity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dexterity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Constitution)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Constitution)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Intelligence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Intelligence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wisdom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wisdom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Charisma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Charisma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BackStory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BackStory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    <div>
    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>
</div>

</body>
</html>

DungeonMasterStudio/Views/CharacterModels/Edit.cshtml
@model DungeonMasterStudio.Models.CharacterModel

@{
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>CharacterModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" class="form-control" />
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Race" class="control-label"></label>
                <input asp-for="Race" class="form-control" />
                <span asp-validation-for="Race" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age1" class="control-label"></label>
                <input asp-for="Age1" class="form-control" />
                <span asp-validation-for="Age1" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Strength" class="control-label"></label>
                <input asp-for="Strength" class="form-control" />
                <span asp-validation-for="Strength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dexterity" class="control-label"></label>
                <input asp-for="Dexterity" class="form-control" />
                <span asp-validation-for="Dexterity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Constitution" class="control-label"></label>
                <input asp-for="Constitution" class="form-control" />
                <span asp-validation-for="Constitution" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Intelligence" class="control-label"></label>
                <input asp-for="Intelligence" class="form-control" />
                <span asp-validation-for="Intelligence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wisdom" class="control-label"></label>
                <input asp-for="Wisdom" class="form-control" />
                <span asp-validation-for="Wisdom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Charisma" class="control-label"></label>
                <input asp-for="Charisma" class="form-control" />
                <span asp-validation-for="Charisma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BackStory" class="control-label"></label>
                <input asp-for="BackStory" class="form-control" />
                <span asp-validation-for="BackStory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

DungeonMasterStudio/Views/CharacterModels/Index.cshtml
@model IEnumerable<DungeonMasterStudio.Models.CharacterModel>

@{
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NPC Generator</title>
</head>
<body>
    <div class="container px-5">
        <h1 class="text-white">Non-Playing Characters</h1>
        <p>
            <a class="btn btn-primary" asp-action="Create">Create New</a>
        </p>
        <div class="row gx-5">
            @foreach (var item in Model)
            {
                <div class="col-sm-4 p-1">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">@item.Name</h3>
                            <p>@item.Date</p>
                            <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.ID">Edit</a> 
                            <a asp-action="Details" class="btn btn-warning" asp-route-id="@item.ID">Details</a> 
                            <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.ID">Delete</a>   
                        </div>
                    </div>         
                </div>
            }
        </div>
        <br>
    </div>
</body>
</html>